# Generated by Django 5.1.1 on 2024-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_comment='IP адрес юзера оценивающего рецензию, защита от накрутки', verbose_name='IP Адрес')),
                ('timestamp', models.DateTimeField(blank=True, db_comment='Время запроса из лога', null=True, verbose_name='Время запроса')),
                ('http_method', models.CharField(db_comment='http метод (GET, POST,...)', default='', max_length=10, verbose_name='http метод')),
                ('uri', models.CharField(db_comment='URI запроса', default='', max_length=255, verbose_name='URI запроса')),
                ('response_code', models.IntegerField(db_comment='Код ответа из лога', default=0, verbose_name='Код ответа')),
                ('response_size', models.IntegerField(db_comment='Размер ответа из лога', default=0, verbose_name='Размер ответа')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'db_table': 'log_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'ip_address'], name='log_data_timesta_b8d001_idx')],
            },
        ),
    ]
